"""Tests for docs/stdlib/pydoc_data.md.

The page's one real cost is that the topic texts arrive all at once, on the
first import of `pydoc_data.topics`, and that `pydoc` defers that import
until a topic is shown. Both are settled in fresh interpreters: by
`sys.modules` and by traced allocation against the total size of the texts.
The lookups and the `module_docs` boundary are settled by observation.

Measurement scope:

* In a fresh interpreter, `import pydoc_data` loads no submodule and the
  package defines no public names. Importing `pydoc_data.topics` leaves more
  traced memory allocated than T bytes, T being the characters of all the
  texts together, and less than 4T, and a second import allocates under 10 KB and returns the
  same module object.
* `topics[label]` returns the same string object on every lookup; every key
  and value is a `str`; the labels the page names are present, and the
  `FORMATTING` topic resolves through `pydoc.Helper.topics` to a label in
  the dict.
* In a fresh interpreter, `import pydoc` loads neither submodule;
  `Helper.help('with')` imports `pydoc_data.topics` and writes the "with"
  text, and a second call leaves the same module in place.
* `pydoc_data.module_docs` is asserted to exist exactly on 3.13.12+ within
  3.13 and on 3.14.3+, maps `json` to `json#module-json`, and is imported by
  `pydoc` only once it looks up a standard-library module's online page.
* `pydoc`'s server handler is asserted to return the text of
  `pydoc_data/_pydoc.css` for the stylesheet URL.
* Every fenced Python block runs in its own subprocess, so none of them
  finds the topics already imported, and a mutated assertion in one of them
  is asserted to fail.

Not settled here:

* `help()`'s O(x) per later topic is read from Lib/pydoc.py: `showtopic()`
  strips one text and wraps its cross-references. It is not timed, and the
  pager it hands the text to is outside the bound.
* Iterating the dict in O(u) and importing `module_docs` in O(m) are the
  cost of a dict and of a module of m literal entries; neither is varied,
  since one interpreter ships one size of each.
* That the texts are regenerated for each release is read from
  Lib/pydoc_data/topics.py's "Autogenerated by Sphinx" header and the
  differing topic counts across 3.10 to 3.14, not asserted.
"""

from __future__ import annotations

import contextlib
import importlib.util
import io
import os
import pathlib
import pydoc
import pydoc_data
import pydoc_data.topics
import re
import subprocess
import sys
import textwrap
from typing import Any

import pytest

PAGE = pathlib.Path(__file__).parent.parent / "docs" / "stdlib" / "pydoc_data.md"
EXPECTED_BLOCKS = 3

HAS_MODULE_DOCS = (3, 13, 12) <= sys.version_info < (3, 14) or sys.version_info >= (3, 14, 3)


def run_python(source: str) -> subprocess.CompletedProcess[str]:
    return subprocess.run(
        [sys.executable, "-c", source],
        capture_output=True,
        text=True,
        timeout=120,
        stdin=subprocess.DEVNULL,
        check=False,
    )


class TestTheTopicsArriveAllAtOnce:
    """`import pydoc_data` | O(1); `import pydoc_data.topics` | O(T) | O(T),
    then O(1) from `sys.modules`. Each run starts a fresh interpreter, so the
    import measured is the first."""

    def test_the_package_import_loads_nothing(self) -> None:
        result = run_python(
            "import sys\n"
            "import pydoc_data\n"
            "print(sorted(m for m in sys.modules if m.startswith('pydoc_data')))\n"
            "print([n for n in vars(pydoc_data) if not n.startswith('__')])\n"
        )
        assert result.returncode == 0, result.stderr
        assert result.stdout.split("\n")[:2] == ["['pydoc_data']", "[]"]

    def test_the_first_import_builds_every_text_and_the_second_builds_nothing(self) -> None:
        result = run_python(
            "import sys, tracemalloc\n"
            "tracemalloc.start()\n"
            "import pydoc_data.topics as first\n"
            "held = tracemalloc.get_traced_memory()[0]\n"
            "tracemalloc.reset_peak()\n"
            "before = tracemalloc.get_traced_memory()[0]\n"
            "import pydoc_data.topics as second\n"
            "again = tracemalloc.get_traced_memory()[1] - before\n"
            "tracemalloc.stop()\n"
            "total = sum(len(text) for text in first.topics.values())\n"
            "print(held, again, total, first is second)\n"
        )
        assert result.returncode == 0, result.stderr
        held, again, total, same = result.stdout.split()

        assert int(total) > 100_000
        assert int(total) < int(held) < 4 * int(total), f"{held} bytes held for {total} characters"
        assert int(again) < 10_000
        assert same == "True"


class TestLookingUpATopic:
    """`topics[label]` | O(1) | O(1): the stored string, under `pydoc`'s own
    labels."""

    def test_a_lookup_returns_the_stored_string(self) -> None:
        topics = pydoc_data.topics.topics
        text = topics["with"]

        assert topics["with"] is text
        assert text.lstrip().startswith('The "with" statement')

    def test_keys_and_values_are_strings(self) -> None:
        topics = pydoc_data.topics.topics

        assert len(topics) > 50
        assert all(isinstance(k, str) and isinstance(v, str) for k, v in topics.items())
        assert "typesseq" in topics

    def test_a_help_topic_name_resolves_to_a_label(self) -> None:
        label, _ = pydoc.Helper.topics["FORMATTING"]

        assert label in pydoc_data.topics.topics


class TestPydocDefersTheImport:
    """`help('with')` | O(T) on the first topic, then O(x): `import pydoc`
    loads nothing, and the first topic imports `pydoc_data.topics`."""

    def test_import_pydoc_loads_no_data_and_help_loads_the_topics(self) -> None:
        result = run_python(
            "import contextlib, io, sys\n"
            "import pydoc\n"
            "print(sorted(m for m in sys.modules if m.startswith('pydoc_data.')))\n"
            "buffer = io.StringIO()\n"
            "with contextlib.redirect_stdout(buffer):\n"
            "    pydoc.Helper(output=buffer).help('with')\n"
            "loaded = sys.modules['pydoc_data.topics']\n"
            "with contextlib.redirect_stdout(buffer):\n"
            "    pydoc.Helper(output=buffer).help('if')\n"
            "print(sorted(m for m in sys.modules if m.startswith('pydoc_data.')))\n"
            "print(sys.modules['pydoc_data.topics'] is loaded)\n"
            "print('The \"with\" statement' in buffer.getvalue())\n"
        )
        assert result.returncode == 0, result.stderr
        lines = result.stdout.splitlines()

        assert lines[0] == "[]"
        assert lines[-3] == "['pydoc_data.topics']"
        assert lines[-2:] == ["True", "True"]


class TestModuleDocs:
    """`pydoc_data.module_docs` | Python 3.13.12+ and 3.14.3+; `pydoc`
    imports it only to link a standard-library module to its online page."""

    def test_it_exists_exactly_from_the_stated_patch_releases(self) -> None:
        found = importlib.util.find_spec("pydoc_data.module_docs") is not None

        assert found == HAS_MODULE_DOCS, sys.version_info

    @pytest.mark.skipif(not HAS_MODULE_DOCS, reason="3.13.12+ and 3.14.3+")
    def test_a_name_maps_to_a_page_and_anchor(self) -> None:
        module_docs: Any = importlib.import_module("pydoc_data.module_docs")

        assert module_docs.module_docs["json"] == "json#module-json"
        assert all(isinstance(v, str) for v in module_docs.module_docs.values())

    @pytest.mark.skipif(not HAS_MODULE_DOCS, reason="3.13.12+ and 3.14.3+")
    def test_pydoc_imports_it_only_to_link_a_module(self) -> None:
        result = run_python(
            "import json, sys\n"
            "import pydoc\n"
            "print('pydoc_data.module_docs' in sys.modules)\n"
            "location = pydoc.TextDoc().getdocloc(json)\n"
            "print('pydoc_data.module_docs' in sys.modules)\n"
            "print(location)\n"
        )
        assert result.returncode == 0, result.stderr
        before, after, location = result.stdout.splitlines()

        assert (before, after) == ("False", "True")
        assert location.endswith("/json#module-json")


class TestTheStylesheet:
    """`_pydoc.css` is the stylesheet the `pydoc -b` browser serves."""

    def test_the_server_returns_the_file(self) -> None:
        handler: Any = pydoc
        path = os.path.join(os.path.dirname(pydoc_data.__file__), "_pydoc.css")
        with open(path, encoding="utf-8") as stylesheet:
            expected = stylesheet.read()

        assert handler._url_handler("pydoc_data/_pydoc.css", "text/css") == expected
        assert expected


def test_help_writes_the_topic_text_here_too() -> None:
    """The same `help()` path in this process, where the topics may already be
    loaded: the output is the stored text."""
    buffer = io.StringIO()
    with contextlib.redirect_stdout(buffer):
        pydoc.Helper(output=buffer).help("with")

    assert pydoc_data.topics.topics["with"].strip() in buffer.getvalue()


def _blocks() -> list[tuple[int, str]]:
    """Every fenced python block on the page, with its 1-based line number."""
    lines = PAGE.read_text(encoding="utf-8").splitlines()
    found: list[tuple[int, str]] = []
    index = 0
    while index < len(lines):
        if re.match(r"^\s*```python\s*$", lines[index]):
            start = index + 1
            end = start
            while not re.match(r"^\s*```\s*$", lines[end]):
                end += 1
            found.append((start + 1, textwrap.dedent("\n".join(lines[start:end]))))
            index = end
        index += 1
    return found


def _run_block(source: str, cwd: pathlib.Path) -> subprocess.CompletedProcess[str]:
    script = cwd / "block.py"
    script.write_text(source, encoding="utf-8")
    return subprocess.run(
        [sys.executable, str(script)],
        cwd=cwd,
        capture_output=True,
        text=True,
        timeout=120,
        stdin=subprocess.DEVNULL,
        check=False,
    )


class TestDocumentedExamples:
    """Each block runs in its own subprocess, so the block asserting that
    `import pydoc` loaded no topics starts from a fresh interpreter."""

    def test_the_page_has_the_expected_blocks(self) -> None:
        assert len(_blocks()) == EXPECTED_BLOCKS

    def test_every_block_runs(self, tmp_path: pathlib.Path) -> None:
        failures: list[str] = []
        ran = 0
        for line, source in _blocks():
            ran += 1
            workdir = tmp_path / f"block{line}"
            workdir.mkdir()
            result = _run_block(source, workdir)
            if result.returncode != 0:
                failures.append(f"{PAGE.name}:{line}\n{result.stderr.strip()}")

        assert ran == EXPECTED_BLOCKS
        assert not failures, "\n\n".join(failures)

    def test_the_runner_notices_a_broken_assertion(self, tmp_path: pathlib.Path) -> None:
        needle = "assert 'pydoc_data.topics' not in sys.modules"
        line, source = next((n, s) for n, s in _blocks() if needle in s)
        mutated = source.replace(needle, "assert 'pydoc_data.topics' in sys.modules", 1)

        assert mutated != source, f"the mutation matched nothing in {PAGE.name}:{line}"
        assert _run_block(mutated, tmp_path).returncode != 0
